name: CI
on:
  push:
      branches: [main]
  pull_request:
      branches: [main]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Cache files
          uses: actions/cache@v2
        - name: Run Codescan On Push
          if: github.event_name == 'push'
          uses: codescan-io/codescan-scanner-action@1.2
          with:
            organization: aradhana5817
            projectKey: Aradhana-Singh-test-temp    
            login: ${{ secrets.codescan_token }}   
            codeScanUrl: https://test.codescan.io/       
        - name: Upload SARIF file
          uses: github/codeql-action/upload-sarif@v1
          with:
            sarif_file: codescan-sarif.json
            
